### ISSUE TITLE
Indexing a 200k single-line CSS file throws java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by rillig-nm** [OpenGrok/OpenGrok#1014]
OpenGrok version: 0.12.1.5
Java version: 1.8.0_31
CSS file: https://www.alpenwelt-versand.com/assets/otto_eu/otto_at/error_files/error_styles2.css (200k, single-line)

    mkdir "./src"
    wget -O "./src/error_styles2.css" "https://www.alpenwelt-versand.com/assets/otto_eu/otto_at/error_files/error_styles2.css"
    java -Xmx512m -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -jar \
      opengrok.jar \
        -a on \
        -d ./oom-data \
        -G \
        -O on \
        -Q off \
        -W conf \
        -r on \
        -s "./src" \
        -v

This command produces the following output:

    Oct 26, 2015 7:45:11 PM org.opensolaris.opengrok.index.IndexDatabase$1 run
    SEVERE: Problem updating lucene index database:
    java.lang.OutOfMemoryError: Java heap space
            at java.util.Arrays.copyOf(Arrays.java:3332)
            at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
            at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
            at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:514)
            at java.lang.StringBuffer.append(StringBuffer.java:352)
            at java.util.regex.Matcher.appendReplacement(Matcher.java:888)
            at java.util.regex.Matcher.replaceAll(Matcher.java:955)
            at java.lang.String.replace(String.java:2227)
            at org.opensolaris.opengrok.analysis.Ctags.readTags(Ctags.java:240)
            at org.opensolaris.opengrok.analysis.Ctags.doCtags(Ctags.java:173)
            at org.opensolaris.opengrok.analysis.plain.PlainAnalyzer.analyze(PlainAnalyzer.java:78)
            at org.opensolaris.opengrok.analysis.AnalyzerGuru.populateDocument(AnalyzerGuru.java:307)
            at org.opensolaris.opengrok.index.IndexDatabase.addFile(IndexDatabase.java:606)
            at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:870)
            at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:383)
            at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:168)

When I replace "}" with "}\n" in the file, indexing still needs some memory but far less. This is probably related to #821, although it is a different analyzer class.

By the way, the “tags” file that is produced by ctags is 536 MB in size.

**Comment by rillig-nm** [comment]
As a workaround, I have added the following code to `Ctags.java`:

                int p = tagLine.indexOf('\t');
                if (p <= 0) {
                    //log.fine("SKIPPING LINE - NO TAB");
                    continue;
                }
    +++         if (tagLine.length() > 50000) {
    +++           continue;
    +++         }
                String def = tagLine.substring(0, p);
                int mstart = tagLine.indexOf('\t', p + 1);

It works for me now, but I have no clue about what I’m doing here and what consequences it has.

**Comment by tarzanek** [comment]
yes, it is definitely #821 and yes your patch mitigates this behaviour a bit, I need to push a fix for this ... (your patch is a start, in case you want to commit it, be my guest and open a pull req, I will gladly accept ;) )

**Comment by tarzanek** [comment]
fwiw - I won't give my +1 for release of 0.13 until this is solved
