### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by pomac303** [OpenGrok/OpenGrok#1035]
Hi,

I added a new project for indexing and was greeted with this:

10:25:37 WARNING: An error occured while creating cache for "project" (GitRepository)
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1931)
    at org.opensolaris.opengrok.history.JDBCHistoryCache.storeHistory(JDBCHistoryCache.java:831)
    at org.opensolaris.opengrok.history.JDBCHistoryCache.store(JDBCHistoryCache.java:672)
    at org.opensolaris.opengrok.history.Repository.createCache(Repository.java:327)
    at org.opensolaris.opengrok.history.HistoryGuru.createCache(HistoryGuru.java:495)
    at org.opensolaris.opengrok.history.HistoryGuru.access$000(HistoryGuru.java:53)
    at org.opensolaris.opengrok.history.HistoryGuru$1.run(HistoryGuru.java:545)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
##     at java.lang.Thread.run(Thread.java:745)

opengrok 0.12.1
db-derby 10.12.1.1
java 1.8.0_66

**Comment by tarzanek** [comment]
@vladak any clues?
also it could be we need a fix for newer derby, not sure what was the latest version we used
(I most probably test with latest derby in my farm tests, but this could have slipped the tests)

**Comment by tulinkry** [comment]
Just for the record, is there any symlink in this project?

**Comment by tulinkry** [comment]
Derby is not supported anymore in the new release hence closing
