### ISSUE TITLE
Too many open files with svn

### ISSUE THREAD

**Issue by dhireng** [OpenGrok/OpenGrok#1043]
Hi,
I get the exception 
SEVERE: Failed to read from process: svn
java.io.IOException: error=24, Too many open files
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:459)
        at org.opensolaris.opengrok.util.Executor.exec(Executor.java:131)
        at org.opensolaris.opengrok.util.Executor.exec(Executor.java:99)
        at org.opensolaris.opengrok.util.Executor.exec(Executor.java:88)
        at org.opensolaris.opengrok.history.SubversionRepository.setDirectoryName(SubversionRepository.java:102)
        at org.opensolaris.opengrok.history.RepositoryFactory.getRepository(RepositoryFactory.java:85)
        at org.opensolaris.opengrok.history.RepositoryFactory.getRepository(RepositoryFactory.java:116)
        at org.opensolaris.opengrok.history.HistoryGuru.invalidateRepositories(HistoryGuru.java:641)
        at org.opensolaris.opengrok.history.HistoryGuru.addRepositories(HistoryGuru.java:359)
        at org.opensolaris.opengrok.index.Indexer.prepareIndexer(Indexer.java:554)
        at org.opensolaris.opengrok.index.Indexer.main(Indexer.java:494)
Caused by: java.io.IOException: java.io.IOException: error=24, Too many open files
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:148)
        at java.lang.ProcessImpl.start(ProcessImpl.java:65)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:452)
        ... 10 more

What's the recommended openfiles settings for opengrok?
My questions may sound fairly basic as I'm new to opengrok. Please let me know what details you need.

**Comment by tarzanek** [comment]
I think this comes from your linux account, see how to add more file handles to your open files limit ...
http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by tarzanek** [comment]
afaik there is no recommended setting, so if you figure one out, let us know

**Comment by tarzanek** [comment]
@dhireng got some number?
I'd be happy to document it in README

**Comment by dhireng** [comment]
Will confirm in 1 or 2 days. The Linux admin finally changed the values today. Tonight's  run will give me the results

**Comment by tarzanek** [comment]
great, curious for the result :)

**Comment by dhireng** [comment]
I have just over 1600 repositories and approx. 65000 files in them. The hard and softlimit of 10240 sufficiently handles new index creation from scratch without any issues

**Comment by tarzanek** [comment]
@dhireng cool stuff!
It's not that bad as I thought! :)
Would you mind forking the repo and editing README and adding this info to tuning section?

tia
L

**Comment by tarzanek** [comment]
I meant here somewhere: https://github.com/OpenGrok/OpenGrok/blob/master/README.txt#L886
into some subsection

**Comment by dhireng** [comment]
closing this as we've got to the bottom of the issue
