### ISSUE TITLE
0.13-rc1 unable to start Web interface

### ISSUE THREAD

**Issue by PawanKulkarniS** [OpenGrok/OpenGrok#1126]
Hi,
 I was trying to bring up Opengrok 0.13-rc1  but it fails to start web-interface with following errors 

# cat catalina.out
Jun 29, 2016 2:29:04 AM org.apache.catalina.core.AprLifecycleListener init
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
Jun 29, 2016 2:29:05 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Jun 29, 2016 2:29:05 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-bio-8009"]
Jun 29, 2016 2:29:05 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 934 ms
Jun 29, 2016 2:29:05 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Jun 29, 2016 2:29:05 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.29
Jun 29, 2016 2:29:05 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /opt/tomcat-instances/opengrok/webapps/source.war
Jun 29, 2016 2:29:06 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Error configuring application listener of class org.opensolaris.opengrok.web.WebappListener
java.lang.UnsupportedClassVersionError: org/opensolaris/opengrok/web/WebappListener : Unsupported major.minor version 52.0 (unable to load class org.opensolaris.opengrok.web.WebappListener)
        at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2905)
        at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1170)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1678)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1556)
        at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:532)
        at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:514)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:133)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5285)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:618)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:963)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1600)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)

Jun 29, 2016 2:29:06 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Skipped installing application listeners due to previous error(s)
Jun 29, 2016 2:29:06 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Jun 29, 2016 2:29:06 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/source] startup failed due to previous errors
Jun 29, 2016 2:29:06 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Jun 29, 2016 2:29:06 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
Jun 29, 2016 2:29:06 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 1073 ms

OS:
Centos 5.9 ,  2.6.18-348.4.1.el5.centos.plus #1 SMP Tue Apr 16 18:51:49 EDT 2013 x86_64 x86_64 x86_64 GNU/Linux

My Java Alternatives 
------------------------------
There are 4 programs which provide 'java'.
  Selection    Command
-----------------------------------------------
   1           /usr/lib/jvm/jre-1.4.2-gcj/bin/java
   2           /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/java
   3           /usr/java/jdk1.7.0_09/bin/java
*+ 4           /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java

Installing and pointed Tomcat's java,javac,jar,jre's to jdk1.8.0_51, jdk1.8.0_91 didn't help

**Comment by tarzanek** [comment]
0.13 needs java8 + tomcat8

**Comment by dethrophes** [comment]
I had this issue and I found a bug in my install.

1. the tomcat8 service script doesn'T support the jre install paths. 
 I fiexd this by editing the script to add the differetn folder paths.

changed 
```
        for jvmdir in /usr/lib/jvm/java-${java_version}-openjdk-* \
                      /usr/lib/jvm/jdk-${java_version}-oracle-* \
                      /usr/lib/jvm/jre-${java_version}-oracle-*
 
```
to
```
        for jvmdir in /usr/lib/jvm/java-${java_version}-openjdk-* \
                      /usr/lib/jvm/jdk-${java_version}-oracle-* \
                      /usr/lib/jvm/java-${java_version}-oracle* \
                      /usr/lib/jvm/jre-${java_version}-oracle-*
```
 
2. edited the catalina.sh script to make it compatible with jre8
https://bugs.launchpad.net/ubuntu/+source/tomcat8/+bug/1586054
bascally remoce the args -Djava.endorsed.dirs from the file /usr/share/tomcat8/bin/catalina.sh


hth
