### ISSUE TITLE
Parsing Erlang re_testoutput1_replacement_test.erl leads to exception

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1138]
When indexing tests from Erlang source code it produces the following exception.

```
INFO: Add: /erlang/otp_src_17.5/lib/stdlib/test/re_testoutput1_replacement_test.erl (ErlangAnalyzer)
Jul 19, 2016 11:15:44 AM org.opensolaris.opengrok.index.IndexDatabase$2 run
SEVERE: Problem updating lucene index database: 
java.lang.Error: Error: could not match input
	at org.opensolaris.opengrok.analysis.erlang.ErlangXref.zzScanError(ErlangXref.java:642)
	at org.opensolaris.opengrok.analysis.erlang.ErlangXref.yylex(ErlangXref.java:868)
	at org.opensolaris.opengrok.analysis.JFlexXref.write(JFlexXref.java:314)
	at org.opensolaris.opengrok.analysis.plain.PlainAnalyzer.writeXref(PlainAnalyzer.java:118)
	at org.opensolaris.opengrok.analysis.plain.PlainAnalyzer.analyze(PlainAnalyzer.java:91)
	at org.opensolaris.opengrok.analysis.plain.AbstractSourceCodeAnalyzer.analyze(AbstractSourceCodeAnalyzer.java:69)
	at org.opensolaris.opengrok.analysis.AnalyzerGuru.populateDocument(AnalyzerGuru.java:354)
	at org.opensolaris.opengrok.index.IndexDatabase.addFile(IndexDatabase.java:622)
	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:883)
	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
	at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:397)
	at org.opensolaris.opengrok.index.IndexDatabase$2.run(IndexDatabase.java:184)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The `re_testoutput1_replacement_test.erl` file is full of funny expressions so the analyzer probably gets confused.

**Comment by vladak** [comment]
[Uploading re-test.zip…]()

**Comment by vladak** [comment]
Tried to upload the file however it failed. It can be extracted from Erlang distribution found on http://www.erlang.org/

**Comment by tarzanek** [comment]
marking as stopper since the whole indexing breaks and won't finish (so this needs some generic solution so this file is skipped and we can continue)

**Comment by tarzanek** [comment]
character ^K breaks the xref generation

**Comment by tarzanek** [comment]
^K is vertical tab or char 11, so I guess we need to somehow parse these invisible chars in erlang ...
