### ISSUE TITLE
Path name not prase properly when they have "-" or "_" in them

### ISSUE THREAD

**Issue by yschandra** [OpenGrok/OpenGrok#1148]
This on 0.13-rc2, from the Android source:

14:15:46 WARNING: An error occured while creating cache for /opt/builds/atlasm-main-la1.1/LINUX/android/external/libusb-compat (GitRepository)
java.lang.IllegalArgumentException: Not a full path: -compat/MODULE_LICENSE_LGPL
	at org.opensolaris.opengrok.history.JDBCHistoryCache.splitPath(JDBCHistoryCache.java:495)
	at org.opensolaris.opengrok.history.JDBCHistoryCache.addAllDirs(JDBCHistoryCache.java:1201)
	at org.opensolaris.opengrok.history.JDBCHistoryCache.getFilesAndDirectories(JDBCHistoryCache.java:1141)
	at org.opensolaris.opengrok.history.JDBCHistoryCache.storeHistory(JDBCHistoryCache.java:780)
	at org.opensolaris.opengrok.history.JDBCHistoryCache.store(JDBCHistoryCache.java:697)
	at org.opensolaris.opengrok.history.Repository.createCache(Repository.java:337)
	at org.opensolaris.opengrok.history.HistoryGuru.createCache(HistoryGuru.java:509)
	at org.opensolaris.opengrok.history.HistoryGuru.access$000(HistoryGuru.java:54)
	at org.opensolaris.opengrok.history.HistoryGuru$1.run(HistoryGuru.java:560)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

14:18:18 WARNING: An error occured while creating cache for /opt/builds/atlasm-main-la1.1/LINUX/android/hardware/libhardware_legacy/wifi (GitRepository)
java.lang.IllegalArgumentException: Not a full path: _legacy/wifi/fusion_copy.h
	at org.opensolaris.opengrok.history.JDBCHistoryCache.splitPath(JDBCHistoryCache.java:495)
	at org.opensolaris.opengrok.history.JDBCHistoryCache.addAllDirs(JDBCHistoryCache.java:1201)
	at org.opensolaris.opengrok.history.JDBCHistoryCache.getFilesAndDirectories(JDBCHistoryCache.java:1141)
	at org.opensolaris.opengrok.history.JDBCHistoryCache.storeHistory(JDBCHistoryCache.java:780)
	at org.opensolaris.opengrok.history.JDBCHistoryCache.store(JDBCHistoryCache.java:697)
	at org.opensolaris.opengrok.history.Repository.createCache(Repository.java:337)
	at org.opensolaris.opengrok.history.HistoryGuru.createCache(HistoryGuru.java:509)
	at org.opensolaris.opengrok.history.HistoryGuru.access$000(HistoryGuru.java:54)
	at org.opensolaris.opengrok.history.HistoryGuru$1.run(HistoryGuru.java:560)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vladak** [comment]
This seems to be specific to JavaDB since I don't see such exception in my testing environment.

**Comment by idodeclare** [comment]
This issue is defunct as of b9a9ac8, "JDBC EOL".
