### ISSUE TITLE
refers to a none-existing or unreadable directory!

### ISSUE THREAD

**Issue by junfx** [OpenGrok/OpenGrok#1157]
``` shell
# run as root
sudo OPENGROK_TOMCAT_BASE=/usr/share/tomcat ./OpenGrok deploy
# run as a normal user
OPENGROK_INSTANCE_BASE=$HOME/opengrok ./OpenGrok index ~/codebase/
```

After clicking (on localhost or remote host) search button on the page:

``` java
There was an error!

The source root specified in your configuration does not point to a valid directory! Please configure your webapp.

The configured dataRoot '/home/xxx/opengrok/data' refers to a none-existing or unreadable directory!

java.security.InvalidParameterException: The configured dataRoot '/home/xxx/opengrok/data' refers to a none-existing or unreadable directory!
    at org.opensolaris.opengrok.web.PageConfig.getDataRoot(PageConfig.java:1153)
    at org.opensolaris.opengrok.web.PageConfig.prepareSearch(PageConfig.java:1173)
    at org.apache.jsp.search_jsp._jspService(search_jsp.java:223)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    .....
    .....
```

And I'm sure sourceRoot and dataRoot in configuration.xml are exist, and:

``` sh
$ ll
total 16
drwxrwxr-x 5 fang fang 4096 Aug  4 14:23 data
drwxrwxr-x 2 fang fang 4096 Aug  4 14:23 etc
drwxrwxr-x 2 fang fang 4096 Aug  4 14:23 log
-rw-rw-r-- 1 fang fang 2741 Aug  4 14:23 logging.properties
```

**Comment by tarzanek** [comment]
permissions for tomcat are not OK to access dirs outside of allowed ones?

**Comment by tarzanek** [comment]
https://github.com/OpenGrok/OpenGrok/wiki/How-to-install-OpenGrok#Optional_setup_of_security_manager_for_tomcat
but it might need some update for tomcat8 ... care to update that doc? (we'd be happy if someone would test and update this section, since most developers use either solaris or own tomcats without security manager)

**Comment by junfx** [comment]
I use default instance base (and src root) /var/opengrok, it works now.
As the doc, it does not work for me or tomcat8, and I'm new to tomcat/java, using opengrok to read C++ codes. Sorry.

**Comment by tulinkry** [comment]
Is this listing from your home?

```log
$ ll
total 16
drwxrwxr-x 5 fang fang 4096 Aug  4 14:23 data
drwxrwxr-x 2 fang fang 4096 Aug  4 14:23 etc
drwxrwxr-x 2 fang fang 4096 Aug  4 14:23 log
-rw-rw-r-- 1 fang fang 2741 Aug  4 14:23 logging.properties
```

I'd like to close this if this is solved.
