### ISSUE TITLE
svn analyzer needs to work with dates ending with *.Z at the end

### ISSUE THREAD

**Issue by ilovemaui** [OpenGrok/OpenGrok#1168]
So I was building an index, and it failed to create history with this error:
Aug 17, 2016 10:44:57 PM org.opensolaris.opengrok.history.SubversionHistoryParser$Handler endElement
SEVERE: Failed to parse: 2010-09-10T20:08:51.Z
java.text.ParseException: Unparseable date: "2010-09-10T20:08:51.Z"
        at java.text.DateFormat.parse(DateFormat.java:366)
        at org.opensolaris.opengrok.history.SubversionHistoryParser$Handler.endElement(SubversionHistoryParser.java:95)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
        at org.opensolaris.opengrok.history.SubversionHistoryParser.processStream(SubversionHistoryParser.java:189)
        at org.opensolaris.opengrok.util.Executor.exec(Executor.java:212)
        at org.opensolaris.opengrok.history.SubversionHistoryParser.parse(SubversionHistoryParser.java:161)
        at org.opensolaris.opengrok.history.SubversionRepository.getHistory(SubversionRepository.java:251)
        at org.opensolaris.opengrok.history.Repository.createCache(Repository.java:306) 
        at org.opensolaris.opengrok.history.HistoryGuru.createCache(HistoryGuru.java:509)
        at org.opensolaris.opengrok.history.HistoryGuru.access$000(HistoryGuru.java:54) 
        at org.opensolaris.opengrok.history.HistoryGuru$1.run(HistoryGuru.java:560)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by tulinkry** [comment]
This should be fixed now. Can you test it?

**Comment by ilovemaui** [comment]
did you want me to test this?

**Comment by tulinkry** [comment]
It's up, it seems to be working, I even added a test case. However I'm interested if it really solved your problem. Thats all.
