### ISSUE TITLE
-A is unable to use ShAnalyzer as a FileAnalyzerFactory

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [OpenGrok/OpenGrok#1183]
Hi,

I am using OpenGrok 12.1.5.

I want to force OpenGrok to use the ShAnalyzer when it encounters files of with the prefix "Makefile." or the suffix ".mk".  Following the [CommandLineOptions.java](https://github.com/OpenGrok/OpenGrok/blob/0.12.1.5/src/org/opensolaris/opengrok/index/CommandLineOptions.java#L75), I added these switches to the command line:

```
-A Makefile.:org.opensolaris.opengrok.analysis.sh.ShAnalyzer
-A .mk:org.opensolaris.opengrok.analysis.sh.ShAnalyzer 

```
It results in the following SEVERE error:

```
23:20:53 SEVERE: Unable to use org.opensolaris.opengrok.analysis.sh.ShAnalyzer as a FileAnalyzerFactory
23:20:53 SEVERE: Stack:
java.lang.InstantiationException: org.opensolaris.opengrok.analysis.sh.ShAnalyzer
        at org.opensolaris.opengrok.index.Indexer.main(Indexer.java:208)
Caused by: java.lang.NoSuchMethodException: org.opensolaris.opengrok.analysis.sh.ShAnalyzer.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.newInstance(Class.java:412)
        at org.opensolaris.opengrok.analysis.AnalyzerGuru.findFactory(AnalyzerGuru.java:433)
        at org.opensolaris.opengrok.analysis.AnalyzerGuru.findFactory(AnalyzerGuru.java:410)
        at org.opensolaris.opengrok.index.Indexer.main(Indexer.java:203)

```
What is the correct way to use the "-A" switch?

Is there a Makefile analyzer that I can readily incorporate?  I know exuberant CTAGS supports Make.

Thanks,
Matt.

**Comment by tarzanek** [comment]
try to use ShAnalyzerFactory ?

**Comment by LiveFreeAndRoam** [comment]
Thankyou tarzanek.  Using ShAnalyzerFactory worked.
