### ISSUE TITLE
History Generation not working

### ISSUE THREAD

**Issue by ganeshgore555** [OpenGrok/OpenGrok#1189]
Have svn properties in config file as below.

OPENGROK_SUBVERSION_USERNAME="name"
OPENGROK_SUBVERSION_PASSWORD="pswd"

When I run command to get history manually on console it works.

But I see below error which doing opengrok indexing.

09:28:10 WARNING: An error occured while creating cache for /cs/pbs/grok/src/summarizer (SubversionRepository)
org.opensolaris.opengrok.history.HistoryException: Failed to get history for: "/cs/pbs/grok/src/summarizer" Exit code: 1
        at org.opensolaris.opengrok.history.SubversionHistoryParser.parse(SubversionHistoryParser.java:162)
        at org.opensolaris.opengrok.history.SubversionRepository.getHistory(SubversionRepository.java:238)
        at org.opensolaris.opengrok.history.Repository.createCache(Repository.java:297)
        at org.opensolaris.opengrok.history.HistoryGuru.createCache(HistoryGuru.java:496)
        at org.opensolaris.opengrok.history.HistoryGuru.ensureHistoryCacheExists(HistoryGuru.java:693)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:349)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:168)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
09:28:11 SEVERE: An error occurred while parsing the xml output
org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 1; XML document structures must start and end within the same entity.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.endEntity(XMLDocumentFragmentScannerImpl.java:903)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.endEntity(XMLDocumentScannerImpl.java:563)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.endEntity(XMLEntityManager.java:1394)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1757)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1408)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2823)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
        at org.opensolaris.opengrok.history.SubversionHistoryParser.processStream(SubversionHistoryParser.java:186)
        at org.opensolaris.opengrok.util.Executor.exec(Executor.java:178)
        at org.opensolaris.opengrok.history.SubversionHistoryParser.parse(SubversionHistoryParser.java:158)
        at org.opensolaris.opengrok.history.SubversionRepository.getHistory(SubversionRepository.java:238)
        at org.opensolaris.opengrok.history.Repository.createCache(Repository.java:297)
        at org.opensolaris.opengrok.history.HistoryGuru.createCache(HistoryGuru.java:496)
        at org.opensolaris.opengrok.history.HistoryGuru.ensureHistoryCacheExists(HistoryGuru.java:693)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:349)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:168)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
09:28:11 WARNING: Non-zero exit status 1 from command [/opt/CollabNet_Subversion/bin/svn, log, --trust-server-cert, --non-interactive, --xml, -v] in directory /cs/pbs/grok/src/tradebookerpublisher: svn: E215004: Authentication failed and interactive prompting is disabled; see the --force-interactive option
svn: E215004: Unable to connect to a repository at URL 'http://odyssey.apps.csintra.net/svn/PBS/tradebookerpublisher/trunk'
svn: E215004: No more credentials or we tried too many times.
Authentication failed

**Comment by tarzanek** [comment]
can you attach debugger (see google on what command line args to provide to java -jar command to have debugger ready and wait until you attach), ideally from netbeans
and set breakpoint to
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/history/SubversionRepository.java#L409
and inspect if all goes well ? if they are properly set? (e.g. there can be extra " or extra whitespace ? )

**Comment by vladak** [comment]
Too old to receive response.
