### ISSUE TITLE
"this ReferenceManager is closed" error with latest version

### ISSUE THREAD

**Issue by kosi2801** [OpenGrok/OpenGrok#1200]
I did an update to latest git version yesterday (2016-10-05) and while it worked flawlessly yesterday today morning i was greeted with following error in the UI when I tried to perform a search:

```
There was an error!

this ReferenceManager is closed

org.apache.lucene.store.AlreadyClosedException: this ReferenceManager is closed
	at org.apache.lucene.search.ReferenceManager.acquire(ReferenceManager.java:98)
	at org.opensolaris.opengrok.configuration.RuntimeEnvironment.getIndexSearcher(RuntimeEnvironment.java:1463)
	at org.opensolaris.opengrok.configuration.RuntimeEnvironment.getMultiReader(RuntimeEnvironment.java:1539)
	at org.opensolaris.opengrok.web.SearchHelper.prepareExec(SearchHelper.java:265)
	at org.apache.jsp.search_jsp._jspService(search_jsp.java:175)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:403)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:347)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:301)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.opensolaris.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:74)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1015)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:652)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1575)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1533)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I could not find any other error or hints in any of the logs apart from that. After Tomcat was restarted the error went away and OpenGrok is currently working as expected.

**Comment by vladak** [comment]
Caused by the changes for PR #1186. I wonder if this could be somehow caused by the double call to searchHelper.destroy() in search.jsp - once directly and second via requestDestroyed() in WebappListener.

**Comment by kosi2801** [comment]
I could reproduce it faster. This error happens immediately after a `./OpenGrok update` execution.

**Comment by vladak** [comment]
Good to know ! Will try to reproduce in house.

**Comment by vladak** [comment]
Given it happens right after index update, my earlier hypothesis about double destroy() is most likely false. Also @tulinkry just reported the same.

**Comment by vladak** [comment]
Looking at refreshSearcherManagerMap(), it seems the algorithm is wrong - it should close only SearcherManager objects for which no project exist.
