### ISSUE TITLE
Issues with 0.13-rc3

### ISSUE THREAD

**Issue by pecastro** [OpenGrok/OpenGrok#1222]
`[root@0823f6051235:/opengrok/bin# ./OpenGrok deploy
Loading the default instance configuration ...

FATAL ERROR: Unable to determine Deployment Directory for  Tomcat - Aborting!

root@0823f6051235:/opengrok/bin# ls -altr /etc/tomcat7/
total 196
-rw-r-----  1 root tomcat7   1530 Jan 25  2014 tomcat-users.xml
-rw-r--r--  1 root tomcat7   1394 Jan 25  2014 context.xml
-rw-r--r--  1 root tomcat7   2370 Feb 21  2014 logging.properties
-rw-r--r--  1 root tomcat7 163065 Sep 16 15:14 web.xml
-rw-r--r--  1 root tomcat7   6500 Sep 16 15:14 server.xml
-rw-r--r--  1 root tomcat7   6426 Sep 16 15:14 catalina.properties
drwxrwxr-x  3 root tomcat7     23 Oct  7 15:48 Catalina
drwxr-xr-x  2 root tomcat7    123 Oct  7 15:48 policy.d
drwxr-xr-x  4 root root       167 Oct  7 15:48 .
drwxr-xr-x 78 root root      4096 Oct 10 20:25 ..
root@0823f6051235:/opengrok/bin# ./OpenGrok version
Loading the default instance configuration ...

Usage: OpenGrok <deploy|derby|update|updateQuietly|usage|help>
       OpenGrok index [<directory>]
       OpenGrok indexpart <src_root> <directory1> [..]
       OpenGrok clearHistory <src_root> <repository_name>

  Optional environment variables:
    OPENGROK_CONFIGURATION - location of your configuration
      e.g. $ OPENGROK_CONFIGURATION=/var/opengrok/myog.conf ./OpenGrok ... 

    See the code for more information on configuration options / variables

root@0823f6051235:/opengrok/bin# ./OpenGrok help
Loading the default instance configuration ...
Options for opengrok.jar:
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/opensolaris/opengrok/index/Indexer : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

Usage: OpenGrok <deploy|derby|update|updateQuietly|usage|help>
       OpenGrok index [<directory>]
       OpenGrok indexpart <src_root> <directory1> [..]
       OpenGrok clearHistory <src_root> <repository_name>

  Optional environment variables:
    OPENGROK_CONFIGURATION - location of your configuration
      e.g. $ OPENGROK_CONFIGURATION=/var/opengrok/myog.conf ./OpenGrok ... 

    See the code for more information on configuration options / variables

root@0823f6051235:/opengrok/bin# java -version
java version "1.7.0_111"
OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-0ubuntu0.14.04.3)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)
`

**Comment by vladak** [comment]
There are 2 problems here:
  1. automatic detection of Tomcat 7 location
  2. failure to run

Ad 1: OpenGrok officially supports Tomcat 8.x and later
Ad 2: seems like a problem with OpenJDK or the way how the binary distribution is produced

**Comment by vladak** [comment]
Given that both problems stem from old software versions, I am closing this issue.
