### ISSUE TITLE
Failure to index root files of a single project directory

### ISSUE THREAD

**Issue by pecastro** [OpenGrok/OpenGrok#1223]
opengrok 0.12.6 seems to ignore the root project files e.g.  base directory, and instead only indexes their directories.

For the base directory files to be indexed you need to create a directory that contains your project and point the indexer at it.

**Comment by vladak** [comment]
How do you run the indexer exactly ?

**Comment by pecastro** [comment]
In the same way as advertised in the docs.
'OPENGROK_VERBOSE=true OPENGROK_INSTANCE_BASE=/tank/opengrok ./OpenGrok index /tank/source'
The output won't list any of the files found in the base dir like README or CHANGELOG...

**Comment by vladak** [comment]
It seems this behavior is caused by the -P option to be used by default by the `OpenGrok` script (in `ENABLE_PROJECTS` variable). For some reason, projects were enabled by default in  cset 5762c9f2 by @tarzanek. There is no way how to change the behavior without modifying the script which seems wrong. thus marking as bug.

**Comment by vladak** [comment]
in the code, the relevant part is in Indexer.java#main:

```
552                /*
553                 * Add paths to directories under source root. If projects
554                 * are enabled the path should correspond to a project because
555                 * project path is necessary to correctly set index directory
556                 * (otherwise the index files will end up in index data root
557                 * directory and not per project data root directory).
558                 * For the check we need to have 'env' already set.
559                 */
560                for (String path : subFilesList) {
561                    String srcPath=env.getSourceRootPath();
562                    if (srcPath==null) { System.err.println("Error getting source root from environment. Exiting.");
563                    System.exit(1);
564                      }
565                    path = path.substring(srcPath.length());
566                    if (env.hasProjects()) {
567                        // The paths need to correspond to a project.
568                        if (Project.getProject(path) != null) {
569                            subFiles.add(path);
570                        } else {
571                            System.err.println("The path " + path
572                                    + " does not correspond to a project");
573                        }
574                    } else {
575                        subFiles.add(path);
576                    }
577                }
578
```

However, in my case, there is nothing printed to stderr for some reason.

**Comment by vladak** [comment]
Removing -P does index all files under source root however the webapp then fails in directory listing with:

```
java.lang.NullPointerException
	at org.apache.jsp.list_jsp._jspService(list_jsp.java:376)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.opensolaris.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1517)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1474)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```
