### ISSUE TITLE
SEVERE: Problem updating lucene index database 

### ISSUE THREAD

**Issue by klshiva4a4** [OpenGrok/OpenGrok#1265]
I am getting below error while indexing code(bunch of C files). (UBUNTU 16.04)
./Opengrok index  ↵

org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource: ChecksumIndexInput(MMapIndexInput(path="/var/opengrok/data/index/segments_1"))): 6 (needs to be between 0 and 1)
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:148)
	at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:329)
	at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:404)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:843)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:694)
	at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:400)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:746)
	at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:330)
	at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:168)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

opengrok sources are downloaded from (https://github.com/OpenGrok/OpenGrok/releases-opengrok-0.12.1.6) 
installed packages : exuberant-ctags tomcat7 openjdk-7-jdk

**Comment by vladak** [comment]
I believe this happens when reindex from scratch is needed.

**Comment by srianirudh84** [comment]
Hi @vladak  How to fix this error ?

**Comment by tarzanek** [comment]
@srianirudh84 delete your data root dir
(rm -rf /var/opengrok/data/* )
and start indexing anew ... closing

**Comment by tarzanek** [comment]
AH, one more thing - use jdk 8 (ideally from Oracle, I think not many people test with openjdk so there might be dragons)

**Comment by tarzanek** [comment]
(and tomcat 8 of course :-D )

**Comment by xiangp126** [comment]
I meet the same error when indexing linux kernel

I used Java 8u172 and tomcat 8

**Comment by tarzanek** [comment]
@xiangp126 please file a new issue a lot has changed since 2016 and 0.12 opengrok version
