### ISSUE TITLE
opengrok-0.13-rc1 search has issues and throws java.lang.NullPointerException ERROR

### ISSUE THREAD

**Issue by PawanKulkarniS** [OpenGrok/OpenGrok#1319]
Dear admin,

   We see that while searching for the string for indexed SVN branch , we see the following exception  
   instead  of redirection to standard output....
-----------------------------------------------
There was an error!

null

java.lang.NullPointerException
	at org.apache.jsp.search_jsp._jspService(search_jsp.java:650)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.opensolaris.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:873)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2508)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

------------------------
expected output.. should be 
" Your search full:sb_jdd did not match any files.
Suggestions:

    Make sure all terms are spelled correctly.
    Try different keywords.
    Try more general keywords.
    Use 'wil*' cards if you are looking for partial match. "

Regards - Pawan Kulkarni .S

**Comment by tulinkry** [comment]
It would be quite helpful if you could provide what is on the line 650 because when I try it, this line is empty for me.

To do it navigate into `CATALINA_BASE` directory (the directory where tomcat has its webapps) > webapps > source > org/apache/jsp/search_jsp.java and paste here the content around line 650.

**Comment by PawanKulkarniS** [comment]
Thanks for looking into this issue.
Please find the snippet, I have also attached the search_jsp.java file for your ref.
    629     } else if (searchHelper.hits == null) {
    630
    631       out.write("<p>No hits</p>");
    632
    633     } else if (searchHelper.hits.length == 0) {
    634         List<Suggestion> hints = searchHelper.getSuggestions();
    635         for (Suggestion hint : hints) {
    636
    637       out.write("<p><font color=\"#cc0000\">Did you mean (for ");
    638       out.print( hint.name );
    639       out.write(")</font>:");
    640
    641             for (String word : hint.freetext) {
    642
    643       out.write("<a href=search?q=");
    644       out.print( word );
    645       out.write('>');
    646       out.print( word );
    647       out.write("</a> &nbsp;  ");
    648
    649             }
    650             for (String word : hint.refs) {
    651
    652       out.write("<a href=search?refs=");
    653       out.print( word );
    654       out.write('>');
    655       out.print( word );
    656       out.write("</a> &nbsp;  ");
    657
    658             }
    659             for (String word : hint.defs) {
    660
    661       out.write("<a href=search?defs=");
    662       out.print( word );
    663       out.write('>');
    664       out.print( word );
    665       out.write("</a> &nbsp;  ");
    666
    667             }
    668
    669       out.write("</p>");
    670
    671         }
    672
    673       out.write("<p> Your search <b>");
    674       out.print( searchHelper.query );
    675       out.write("</b> did not match any files.\n");

**Comment by tulinkry** [comment]
Are you sure that you use 0.13-rc1? Because checks for the null have been added in #659 which is in 2013 - a long time ago before 0.13-rc1.

Current code in rc1 (also in rc5) is [here](https://github.com/OpenGrok/OpenGrok/blob/0.13-rc1/web/search.jsp#L151-L156) where it's not possible to get an exception on the same line.

**Comment by tulinkry** [comment]
No reaction for a month, hence closing
