### ISSUE TITLE
history parser exceptions lack file info

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1323]
Often I see great number of exceptions like this in indexer logs:

```
Jan 14, 2017 12:04:33 AM org.opensolaris.opengrok.history.SCCSHistoryParser initFields
WARNING: An error occured while parsing date
java.text.ParseException: Unparseable date: ":0/02/07 15:25:57"
        at java.text.DateFormat.parse(DateFormat.java:366)
        at org.opensolaris.opengrok.history.SCCSHistoryParser.initFields(SCCSHistoryParser.java:130)
        at org.opensolaris.opengrok.history.SCCSHistoryParser.getRevision(SCCSHistoryParser.java:149)
        at org.opensolaris.opengrok.history.SCCSHistoryParser.parseFile(SCCSHistoryParser.java:90)
        at org.opensolaris.opengrok.history.SCCSHistoryParser.parse(SCCSHistoryParser.java:68)
        at org.opensolaris.opengrok.history.SCCSRepository.getHistory(SCCSRepository.java:261)
        at org.opensolaris.opengrok.history.FileHistoryCache.get(FileHistoryCache.java:499)
```

The problem is that they are impossible to pair with actual file that caused it. Seems like bunch of history parsers exhibit the pattern of catching the `ParseException` and just logging it.

**Comment by tulinkry** [comment]
These date format exceptions are more expressive with #1336
