### ISSUE TITLE
null ptr exception in getSearchTitle()

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1398]
With 0.13-rc9 the following exception is seen:

```
java.lang.NullPointerException
        at org.opensolaris.opengrok.web.PageConfig.getSearchTitle(PageConfig.java:1361)
        at org.apache.jsp.search_jsp._jspService(search_jsp.java:264)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.opensolaris.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:55)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.opensolaris.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:66)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

This usually happens after Tomcat is restarted and disappears when the page is refreshed.

**Comment by vladak** [comment]
The code in question:

```
1358     public String getSearchTitle() {
1359         String title = new String();
1360 
1361         if (req.getParameter("q") != null && !req.getParameter("q").isEmpty()) {
1362             title += req.getParameter("q") + " (full)";
1363         }
```

It looks like `req` is null when this happens.

**Comment by vladak** [comment]
Need to reliably reproduce this first.

**Comment by tulinkry** [comment]
Req can be null if the request has been destroyed already. Is this exactly rc9? It could be the #1392 problem

**Comment by vladak** [comment]
I think this happened after upgrade to rc9 however it might be still with the old webapp deployed. I was kind of hoping that the fix for #1392 would resolve the issue, let's see how rc10 will do.

**Comment by vladak** [comment]
While going through the changes for PR #1415 , I found this comment at the top of `PageConfig.java`:

```
70  * A simple container to lazy initialize common vars wrt. a single request. It
71  * MUST NOT be shared between several requests and
72  * {@link #cleanup(ServletRequest)} should be called before the page context
73  * gets destroyed (e.g.when leaving the {@code service} method).
```

Given that `getSearchTitle()` is does exactly what the comment warns against in `search.jsp`:

```
58 /* ---------------------- search.jsp start --------------------- */
59 {
60     cfg = PageConfig.get(request);

...

85         cfg.setTitle(cfg.getSearchTitle());
```

it seems plausible that the `req` in PageConfig instance might be nullified with `cleanup()` since `cfg` is shared between requests.

**Comment by vladak** [comment]
Haven't seen this in 0.13-rc10, closing for now.
