### ISSUE TITLE
0.13 webapp won't start if config dir / file doesn't exist - regression

### ISSUE THREAD

**Issue by tarzanek** [OpenGrok/OpenGrok#1413]
0.12 used to start even without config.xml readable,
0.13 however does:
Feb-2017 17:07:51.941 WARNING [localhost-startStop-1] org.opensolaris.opengrok.web.WebappListener.contextInitialized OpenGrok Configuration error. Failed to read config file:
 java.io.FileNotFoundException: /var/opengrok/etc/configuration.xml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.opensolaris.opengrok.configuration.Configuration.read(Configuration.java:788)
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.readConfiguration(RuntimeEnvironment.java:905)
        at org.opensolaris.opengrok.web.WebappListener.contextInitialized(WebappListener.java:58)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

and the webapp fails to start (repro on mac os x with howto from https://blog.simplypatrick.com/posts/2015/01-16-opengrok-on-mac-osx/ )
@nerakhon reported this ...

**Comment by tarzanek** [comment]
we should wrap above and don't die, but wait for config to be sent as in 0.12

**Comment by vladak** [comment]
After I moved `/var/opengrok/etc/configuration.xml` aside I got this with 0.13-rc8:

![nocfg](https://cloud.githubusercontent.com/assets/2934284/22942354/7833c20e-f2e9-11e6-80ed-34c7f8e3c247.png)

there are these notable things about it:
  - no CSS
  - null ptr even with what seems correct error message
  - bogus info about last index time

**Comment by vladak** [comment]
Just tried 0.12.1.6 and the webapp indeed comes up clean without configuration.xml.

**Comment by vladak** [comment]
Thinking of this again, the behavior of 0.12 (i.e. displaying the front page without any indication of state) seems not correct to me either. The front page should at least say that configuration needs to be created.

**Comment by tulinkry** [comment]
I'm on that side that the webapp should start but should inform the user that it can't do anything until the user will run the index

**Comment by nerakhon** [comment]
Yep the problem is that the JSP container totally fails to deploy in 0.13 which is totally confusing. Especially given the fact configuration will be pushed with the indexer run.

**Comment by ozankiraz** [comment]
Pull request #1431 tested with U command line option, looks like working fine.

**Comment by ozankiraz** [comment]
Created new PR #1440

**Comment by ozankiraz** [comment]
Covered in PR #1453
