### ISSUE TITLE
Method renamed kills startup after upgrade.

### ISSUE THREAD

**Issue by idodeclare** [OpenGrok/OpenGrok#1454]
Hello,

I'm used to upgrading source.war and also possibly deleting data/ to cause a re-index, but RCs after Jan 16 won't start up due to the exception below.

The renaming commit of interest is [deduplication of date formats in repositories](https://github.com/OpenGrok/OpenGrok/commit/9a1b09f63b65e049aca44a0ca5d8fd4fd40e0da7#diff-7f2da3d8b0097ed4335d2c230d773e13).

Do you have upgrade advice?

Thank you.

```
 java.io.IOException: java.lang.NoSuchMethodException: <unbound>=RepositoryInfo.setDatePattern("EE, d MMM yyyy HH:mm:ss Z");
        at org.opensolaris.opengrok.configuration.Configuration.decodeObject(Configuration.java:1057)
        at org.opensolaris.opengrok.configuration.Configuration.read(Configuration.java:1022)
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.readConfiguration(RuntimeEnvironment.java:1139)
        at org.opensolaris.opengrok.web.WebappListener.contextInitialized(WebappListener.java:74)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4842)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5303)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by tarzanek** [comment]
which java is used to run your webapp container?
jdk8 ?

also I have experience that the best thing for tomcat is to stop it, completely erase all "source" stuff from webapp and then dump there the war and start tomcat anew ...

**Comment by idodeclare** [comment]
Yes, I do use jdk8.

I see the problem is the existing etc/configuration.xml (e.g., below which has "datePattern" and not the new "datePatterns"). I am used to shunting data/ when a release advises that "reindexing is required" but then deploying OpenGrok and verifying source.war starts up before doing an actual reindexing and a deletion of old data/.

Going forward, I can also remove etc/configuration.xml when a release indicates that "reindexing is required" before verifying that the new source.war starts up.

```
   <void method="add">
    <object class="org.opensolaris.opengrok.history.RepositoryInfo">
     <void property="branch">
      <string>master</string>
     </void>
     <void property="currentVersion">
      <string>2016-12-15 13:03: 497c716 Ken Murchison explicitly declare gethostname() for those Sun platforms that don&apos;t</string>
     </void>
     <void property="datePattern">
      <string>EE, d MMM yyyy HH:mm:ss Z</string>
     </void>
     <void property="directoryName">
      <string>/var/opengrok/src/cyrus-sasl</string>
     </void>
     <void property="parent">
      <string>git@github.com:cyrusimap/cyrus-sasl.git</string>
     </void>
     <void property="type">
      <string>git</string>
     </void>
    </object>
   </void>

```

**Comment by tulinkry** [comment]
You have to run reindex (not necenecessarily from scratch) and the configuration will get updated with the recent code changes.

The application reads the configuration when it starts so you have to run the reindex before the app starts so it contains valid configuration for the upgraded OpenGrok.

**Comment by idodeclare** [comment]
Understood. Thank you.
