### ISSUE TITLE
Project.getByName() needs to perform exact check of project name

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1541]
Let's assume that `foo` and `bar` are valid project names. If the following URL is constructed:

```
https://grok/source/search?project=foo/bar&q=foo&defs=&refs=&path=&hist=&type=
```

this results in 2 exceptions:

```
 org.apache.lucene.index.IndexNotFoundException: no segments* file found in MMapDirectory@/opengrok-1.0/data/index/foo/bar lockFactory=org.apache.lucene.store.NativeFSLockFactory@49cd9676: files: 
[]
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:687)
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:77)
        at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
        at org.apache.lucene.search.SearcherManager.<init>(SearcherManager.java:125)
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.getIndexSearcher(RuntimeEnvironment.java:1916)
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.getMultiReader(RuntimeEnvironment.java:1981)
        at org.opensolaris.opengrok.web.SearchHelper.prepareExec(SearchHelper.java:261)
        at org.apache.jsp.search_jsp._jspService(search_jsp.java:250)
...

21-Apr-2017 14:19:18.039 SEVERE [http-nio-8888-exec-5] org.opensolaris.opengrok.configuration.RuntimeEnvironment.getMultiReader cannot get IndexReader for project foo/bar
 java.lang.NullPointerException
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.getMultiReader(RuntimeEnvironment.java:1982)
        at org.opensolaris.opengrok.web.SearchHelper.prepareExec(SearchHelper.java:261)
        at org.apache.jsp.search_jsp._jspService(search_jsp.java:250)
...
```

The correct URL is

```
https://grok/source/search?project=foo&project=bar&q=foo&defs=&refs=&path=&hist=&type=
```

The project parameters should be checked against list of projects before passing them to `searchHelper`.

**Comment by vladak** [comment]
It turns out the list is checked in `Project.getByName()` which is called from `PageConfig.getRequestedProjects()` however the match is done using `indexOf()` so if one of the projects in `RuntimeEnvironment` is a prefix of the bogus project, it is returned as valid.
