### ISSUE TITLE
Corrupted indexes with file mismatch

### ISSUE THREAD

**Issue by wrporter** [OpenGrok/OpenGrok#1637]
I'm getting the following corrupted index error message when attempting to index OpenGrok.

```
/var/opengrok/bin # ./OpenGrok index
Loading the default instance configuration ...
Logging filehandler pattern: /var/opengrok/log/opengrok%g.%u.log
21:35:42 SEVERE: Problem updating lucene index database:
org.apache.lucene.index.CorruptIndexException: file mismatch, expected id=8nkmec53e0tdvyrhj7oz0b67a, got=6z7xlm42k05z1sn49h1i5wb3h (resource=MMapIndexInput(path="/var/opengrok/data/index/monolith/_g6_Lucene50_0.doc"))
	at org.apache.lucene.codecs.CodecUtil.checkIndexHeaderID(CodecUtil.java:348)
	at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:256)
	at org.apache.lucene.codecs.lucene50.Lucene50PostingsReader.<init>(Lucene50PostingsReader.java:82)
	at org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat.fieldsProducer(Lucene50PostingsFormat.java:442)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsReader.<init>(PerFieldPostingsFormat.java:292)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat.fieldsProducer(PerFieldPostingsFormat.java:372)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:112)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:74)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:62)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:54)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:692)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:77)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
	at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:368)
	at org.opensolaris.opengrok.index.IndexDatabase$2.run(IndexDatabase.java:184)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I'm uncertain as to how we got in this state. What's the best way to resolve this issue? Anything besides nuking the data directory and doing a full re-index?

OpenGrok version: 1.0
OS: Alpine
Running on a Docker container
Tomcat version: 8
JDK: 8

**Comment by tarzanek** [comment]
just nuke the "monolith" directory in data, if possible, leave the rest, OpenGrok will just refresh this project, if the rest of projects inside data is OK, then leave them.
I don't think any other fix would be feasible.

**Comment by wrporter** [comment]
@tarzanek Thanks for the suggestion, I actually tried that just after creating this issue. For the first 20 minutes or so, when attempting to index, I got errors like the following.

```
2017-06-19 21:58:34.282+0000 WARNING t3270 IndexDatabase.indexDown: Failed to add file /var/opengrok/src/monolith/brands/Brands/olemissmktg/olemissalum/PageIcon.gif
org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:747)
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:761)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1565)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1314)
	at org.opensolaris.opengrok.index.IndexDatabase.addFile(IndexDatabase.java:635)
	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:883)
	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
	at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:397)
	at org.opensolaris.opengrok.index.IndexDatabase$2.run(IndexDatabase.java:184)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: /var/opengrok/data/index/monolith/_0.fdx
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.size(Files.java:2332)
	at org.apache.lucene.store.FSDirectory.fileLength(FSDirectory.java:243)
	at org.apache.lucene.index.SegmentCommitInfo.sizeInBytes(SegmentCommitInfo.java:209)
	at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:521)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:481)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:539)
	at org.apache.lucene.index.DocumentsWriter.postUpdate(DocumentsWriter.java:396)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:499)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1569)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1314)
	at org.opensolaris.opengrok.index.IndexDatabase.addFile(IndexDatabase.java:635)
	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:883)
	... 10 more
```

After waiting, I ran another index and the indexes were repaired. 

Do you have any information as to how one might get into this corrupted index state and how to avoid it? Also, any idea on the `AlreadyClosedException`s and if I have to go through this process again, what the best way is to delete something from the data directory and reindex?

**Comment by tarzanek** [comment]
the AlreadyClosedException comes from old index process running around while you deleted its contents
so always delete dirs when the box has no running indexers

how the corruption happens I have no clue, you know what you did with the container ... (anything is possible)

**Comment by wrporter** [comment]
@tarzanek Thanks for the quick response! Closing this out.
