### ISSUE TITLE
Travis failed with NPE in IndexerRepoTest

### ISSUE THREAD

**Issue by tulinkry** [OpenGrok/OpenGrok#1666]
Yesterday our build failed (after integrating #1643 @vladak), not sure what happened but we shouldn't forget about it.

https://travis-ci.org/OpenGrok/OpenGrok/builds/253203610

```log
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.552 s <<< FAILURE! - in org.opensolaris.opengrok.index.IndexerRepoTest
[ERROR] testMainWithoutH(org.opensolaris.opengrok.index.IndexerRepoTest)  Time elapsed: 2.751 s  <<< ERROR!
java.lang.NullPointerException
	at org.opensolaris.opengrok.index.IndexerRepoTest.checkNumberOfThreads(IndexerRepoTest.java:82)
	at org.opensolaris.opengrok.index.IndexerRepoTest.testMainWithoutH(IndexerRepoTest.java:113)
```

**Comment by vladak** [comment]
The method looks like this:

```
71      private void checkNumberOfThreads() {
72          /*
73           * There should not be any threads in the renamed pool now.
74           * We need to check it like this since the test framework tears
75           * down the threads at the end of the test case run so any
76           * hangs due to executors not being shut down would not be visible.
77           */
78          ThreadGroup mainGroup = Thread.currentThread().getThreadGroup();
79          Thread[] threads = new Thread[mainGroup.activeCount()];
80          mainGroup.enumerate(threads);
81          for (int i = 0; i < threads.length; i++) {
82              if (threads[i].getName() == null) {
83                  continue;
84              }
85              assertEquals(false, threads[i].getName().contains("renamed-handling"));
86          }
87      }
```

So it seems `threads[i]` for a `i` was `null`.
