### ISSUE TITLE
Error while executing Junit Tests in OpenGrok-1.0

### ISSUE THREAD

**Issue by ParmeetSingh** [OpenGrok/OpenGrok#1671]
Running org.opensolaris.opengrok.analysis.CtagsTest
Jul 17, 2017 10:14:06 PM org.opensolaris.opengrok.analysis.Ctags initialize
INFO: Adding extra options to ctags
Jul 17, 2017 10:14:06 PM org.opensolaris.opengrok.analysis.Ctags$1 run
WARNING: Error from ctags: ctags: Unknown option: --c-kinds

Jul 17, 2017 10:14:06 PM org.opensolaris.opengrok.util.IOUtils close
WARNING: Failed to close resource: 
java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
	at org.opensolaris.opengrok.util.IOUtils.close(IOUtils.java:59)
	at org.opensolaris.opengrok.analysis.Ctags.close(Ctags.java:75)
	at org.opensolaris.opengrok.analysis.CtagsTest.tearDownClass(CtagsTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.856 sec <<< FAILURE! - in org.opensolaris.opengrok.analysis.CtagsTest
bug14924(org.opensolaris.opengrok.analysis.CtagsTest)  Time elapsed: 0.045 sec  <<< ERROR!
java.io.IOException: Stream closed
	at org.opensolaris.opengrok.analysis.CtagsTest.getDefs(CtagsTest.java:95)
	at org.opensolaris.opengrok.analysis.CtagsTest.bug14924(CtagsTest.java:118)

Results :

Tests in error: 
  CtagsTest.bug14924:118->getDefs:95 ? IO Stream closed

**Comment by tarzanek** [comment]
please use exuberant ctags or ideally universal ctags

**Comment by ParmeetSingh** [comment]
Hey,
I am using universal Ctags. I am running the test using :
mvn  test -Dtest=CtagsTest -DfailIfNoTests=false

I have included these in my classpath:
export PATH=$PATH:/home/utils/ctags-5.8/bin 
export EXUBERANT_CTAGS=/home/utils/ctags-5.8/bin/ctags.

Still I am getting this error.Can you guide me on the way I need to include these while running unit tests?

**Comment by tarzanek** [comment]
(above might work too with  export PATH=/home/utils/ctags-5.8/bin:$PATH    - note I made exctags to be first in search before anything else from system)
BUT exuberant ctags 5.8 is really really old, 5.9 should work (since travis uses them:  https://travis-ci.org/OpenGrok/OpenGrok )

BUT universal ctags are here:
https://github.com/universal-ctags/ctags

git clone them, build and set proper paths, then it should work even better than with any other ctags
(and make sure they are the first in path)

**Comment by vladak** [comment]
Note that the environment variable `EXUBERANT_CTAGS` was renamed to `OPENGROK_CTAGS` in 1.1.

**Comment by vladak** [comment]
Overall, the problem stems from this:

```
Unknown option: --c-kinds
```

i tried Exuberant ctags 5.8 and the latest Universal ctags and both work fine w.r.t. this option.

Can you figure out what ctags binary and with what arguments is actually being run (easy with `execsnoop` from Dtrace toolkit)

**Comment by tarzanek** [comment]
@vladak his path is wrong, exctags are last, so first ones are the ones from system, which are obviously common ctags

**Comment by ParmeetSingh** [comment]
Below worked for me. Thanks a lot @vladak and @tarzanek .

(above might work too with export PATH=/home/utils/ctags-5.8/bin:$PATH - note I made exctags to be first in search before anything else from system)
