### ISSUE TITLE
IndexDatabase.getFiles functionality needs to be investigated

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1676]
When working on test case for #767 I wanted to peruse modified version (so that it returns set of strings instead of writing them to the log) of `IndexDatabase#listFiles()` and call it like this:

```
Assert.assertEquals(6, idb.getFiles().size());
```

however got exception instead:

```
Testcase: testCleanupAfterIndexRemoval(org.opensolaris.opengrok.index.IndexDatabaseTest):	Caused an ERROR
String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.opensolaris.opengrok.web.Util.uid2url(Util.java:647)
	at org.opensolaris.opengrok.index.IndexDatabase.getFiles(IndexDatabase.java:1028)
	at org.opensolaris.opengrok.index.IndexDatabaseTest.testCleanupAfterIndexRemoval(IndexDatabaseTest.java:164)
```

This is curious feature anyway that is being called from `Indexer#prepareIndexer`:

```
789          if (listFiles) {
790              IndexDatabase.listAllFiles(subFiles);
791          }
```

however the `listFiles` boolean does not have a matching option so likely this code path has not been called for a long time. Hence filing this issue so that it is not forgotten. Either it should be fixed or ripped out.

**Comment by vladak** [comment]
Same code for terms traversal is used in `IndexDatabase#update()` and looks correct according to https://stackoverflow.com/questions/15290980/how-to-get-all-terms-for-a-lucene-field-in-lucene-4 so maybe this was something special about the test `testCleanupAfterIndexRemoval()` in cset d3dbeace66e057e715f6ca50906fd209a649fede - try to replace the call to `idb.getNumFiles()` with `getFiles().size()`.
