### ISSUE TITLE
Projects have to be enabled - incovenient migration

### ISSUE THREAD

**Issue by tulinkry** [OpenGrok/OpenGrok#1678]
Using OpenGrok without projects (or now just indexing after #1663) indexer emits several times an exception (one per project I guess):

```log
Jul 24, 2017 11:50:25 AM org.opensolaris.opengrok.index.IndexDatabase$2 run
SEVERE: Problem updating lucene index database: 
java.io.IOException: Message was not accepted by the remote server - Projects have to be enabled in order to use this message (error 0x4).
	at org.opensolaris.opengrok.configuration.messages.Message.throwIfError(Message.java:385)
	at org.opensolaris.opengrok.configuration.messages.Message.write(Message.java:307)
	at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:423)
	at org.opensolaris.opengrok.index.IndexDatabase$2.run(IndexDatabase.java:186)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

As a result no project is displayed on the main page and one has to run the indexer twice or restart the webapplication (the configuration.xml already contains the projectsEnabled = true after the first run).

Problems:
1. It should not be a problem to turn on projects when application is already running
2. It should not be a problem to migrate to PR #1663

**Comment by vladak** [comment]
The problem stems from the fact that the configuration is sent to the webapp by the Indexer only after it is done indexing however after #1663 the indexer is sending `project` Messages (with text `indexed` to mark given project indexed) before that. The message is strictly checked and the webapp does not have the configuration, hence the error.

**Comment by vladak** [comment]
To make the transition easier, `config` Message can be sent to the webapp with `projectsEnabled = true` (if running with -P) before the indexing takes place.
