### ISSUE TITLE
ClassCastException when handling authorization

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1826]
On 1.1-rc16 just after reloading authorization plugins (via `Message`) Tomcat reported these exceptions in the log:

```
17-Oct-2017 18:03:17.385 WARNING [http-nio-8888-exec-82] org.opensolaris.opengrok.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.LdapAttr" has failed the testing of "XXX" with an exception.
 java.lang.ClassCastException: opengrok.auth.entity.LdapUser cannot be cast to opengrok.auth.entity.LdapUser
        at opengrok.auth.plugin.LdapAttr.fillSession(LdapAttr.java:88)
        at opengrok.auth.plugin.AbstractLdapPlugin.ensureSessionExists(AbstractLdapPlugin.java:266)
        at opengrok.auth.plugin.AbstractLdapPlugin.isAllowed(AbstractLdapPlugin.java:359)
        at org.opensolaris.opengrok.authorization.AuthorizationFramework$3.decision(AuthorizationFramework.java:199)
        at org.opensolaris.opengrok.authorization.AuthorizationPlugin.isAllowed(AuthorizationPlugin.java:187)
        at org.opensolaris.opengrok.authorization.AuthorizationStack.processStack(AuthorizationStack.java:238)
        at org.opensolaris.opengrok.authorization.AuthorizationStack.isAllowed(AuthorizationStack.java:199)
        at org.opensolaris.opengrok.authorization.AuthorizationStack.processStack(AuthorizationStack.java:238)
        at org.opensolaris.opengrok.authorization.AuthorizationStack.isAllowed(AuthorizationStack.java:199)
        at org.opensolaris.opengrok.authorization.AuthorizationFramework.performCheck(AuthorizationFramework.java:713)
        at org.opensolaris.opengrok.authorization.AuthorizationFramework.checkAll(AuthorizationFramework.java:678)
        at org.opensolaris.opengrok.authorization.AuthorizationFramework.isAllowed(AuthorizationFramework.java:192)
        at org.opensolaris.opengrok.web.PageConfig.isAllowed(PageConfig.java:1488)
        at org.opensolaris.opengrok.web.ProjectHelper$2.test(ProjectHelper.java:180)
        at org.opensolaris.opengrok.web.ProjectHelper$2.test(ProjectHelper.java:177)
        at java.util.Collection.removeIf(Collection.java:414)
        at org.opensolaris.opengrok.web.ProjectHelper.filterGroups(ProjectHelper.java:177)
        at org.opensolaris.opengrok.web.ProjectHelper.cacheGroups(ProjectHelper.java:214)
        at org.opensolaris.opengrok.web.ProjectHelper.getGroups(ProjectHelper.java:224)
        at org.opensolaris.opengrok.web.ProjectHelper.populateGroups(ProjectHelper.java:145)
        at org.opensolaris.opengrok.web.ProjectHelper.<init>(ProjectHelper.java:87)
        at org.opensolaris.opengrok.web.ProjectHelper.getInstance(ProjectHelper.java:101)
        at org.apache.jsp.enoent_jsp._jspService(enoent_jsp.java:308)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:469)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:392)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311)
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:395)
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:254)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:177)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

so these appear to be related to `enoent` (404 error) handling.

later on there was another shower of `ClassCastException` but with different stack:

```
17-Oct-2017 18:23:23.285 WARNING [http-nio-8888-exec-81] org.opensolaris.opengrok.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.LdapFilter" has failed the testing of "
XXX" with an exception.
 java.lang.ClassCastException: opengrok.auth.entity.LdapUser cannot be cast to opengrok.auth.entity.LdapUser
        at opengrok.auth.plugin.LdapFilter.fillSession(LdapFilter.java:73)
        at opengrok.auth.plugin.AbstractLdapPlugin.ensureSessionExists(AbstractLdapPlugin.java:266)
        at opengrok.auth.plugin.AbstractLdapPlugin.isAllowed(AbstractLdapPlugin.java:348)
        at org.opensolaris.opengrok.authorization.AuthorizationFramework$1.decision(AuthorizationFramework.java:161)
        at org.opensolaris.opengrok.authorization.AuthorizationPlugin.isAllowed(AuthorizationPlugin.java:187)
        at org.opensolaris.opengrok.authorization.AuthorizationStack.processStack(AuthorizationStack.java:238)
        at org.opensolaris.opengrok.authorization.AuthorizationStack.isAllowed(AuthorizationStack.java:199)
        at org.opensolaris.opengrok.authorization.AuthorizationStack.processStack(AuthorizationStack.java:238)
        at org.opensolaris.opengrok.authorization.AuthorizationStack.isAllowed(AuthorizationStack.java:199)
        at org.opensolaris.opengrok.authorization.AuthorizationFramework.performCheck(AuthorizationFramework.java:713)
        at org.opensolaris.opengrok.authorization.AuthorizationFramework.checkAll(AuthorizationFramework.java:678)
        at org.opensolaris.opengrok.authorization.AuthorizationFramework.isAllowed(AuthorizationFramework.java:154)
        at org.opensolaris.opengrok.web.PageConfig.isAllowed(PageConfig.java:1479)
        at org.opensolaris.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:56)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

17-Oct-2017 18:23:23.285 INFO [http-nio-8888-exec-81] org.opensolaris.opengrok.web.AuthorizationFilter.doFilter Access denied for URI: /source/xref/XXX
```

It seems that these exceptions were happening for requests of one particular user. His requests were basically going like this:

```
IP_ADDRESS - USER@DOMAIN [17/Oct/2017:17:59:49 +0200] "GET /source/xref/foo/bar.ksh HTTP/1.1" 302 20
IP_ADDRESS - USER@DOMAIN [17/Oct/2017:17:59:50 +0200] "GET /source/xref/foo/bar.ksh?r=889%3A5210de6cd796 HTTP/1.1" 200 
3777
IP_ADDRESS - USER@DOMAIN [17/Oct/2017:18:00:04 +0200] "GET /source/js/searchable-option-list-2.0.3.min.js HTTP/1.1" 404 2225
IP_ADDRESS - USER@DOMAIN [17/Oct/2017:18:00:04 +0200] "GET /source/js/utils-0.0.13.js HTTP/1.1" 404 3074
IP_ADDRESS - USER@DOMAIN [17/Oct/2017:18:00:05 +0200] "GET /source/xref/foo/usr/src/tools/ HTTP/1.1" 403 464
IP_ADDRESS - USER@DOMAIN [17/Oct/2017:18:00:06 +0200] "GET /favicon.ico HTTP/1.1" 200 318
```

The 404 errors are also interesting (although probably not related), seems like something went wrong with caching as these JS files have version from older 1.1 RCs than what the server is running.

After cca half an hour they stopped appearing, possibly because the user stopped accessing the service. After that another authorization reload happened and the user retried and his requests went through just fine. That day the authorization stack configuration has not changed.

@tulinkry do you have some idea how this can happen ?

**Comment by vladak** [comment]
I realize this references the source code supplied via #1620, hopefully it will be made available soon.

**Comment by vladak** [comment]
Also, one important thing - requests from different users in the same period (the hour between authorization plugin reloads) did not have this problem.

**Comment by tulinkry** [comment]
I suspect the class loading specifics - the class is identified by a name and a classloader. I think that we store a reference to a class in the session (the user), then the class is reloaded when plugins are reloaded (=> it is different class as the previous class loader was discarded and a new was created) and then these two are incompatibile (because of different class loaders)

**Comment by vladak** [comment]
Ah, sounds like a bug to me then.

**Comment by tulinkry** [comment]
Indeed

**Comment by vladak** [comment]
Now that authorization plugins are part of the code, the above stack traces can be tied back to the code. For the `LdapAttr` (which has been renamed to `LdapAttrPlugin`) the code leading to the exception looks like this:

```
85      public void fillSession(HttpServletRequest req, User user) {
86          Boolean sessionAllowed = false;
87          LdapUser ldapUser;
88          Map<String, Set<String>> records;
89          Set<String> attributes;
90  
91          updateSession(req, sessionAllowed);
92  
93          if ((ldapUser = (LdapUser) req.getSession().getAttribute(LdapUserPlugin.SESSION_ATTR)) == null) {
94              return;
95          }
```

i.e. the cast on line 93.

Such construction is present also in `LdapFilterPlugin`.

I guess the exception can be catched and the attribute removed. Another solution might be to invalidate the attributes for all sessions on plugin reload.

**Comment by vladak** [comment]
Another approach might be to avoid storing objects in the session and store their representation (XML encoding ?) only however by itself this does not solve the problem with object properties changing in between plugin reloads.

**Comment by vladak** [comment]
There is actually a test for session invalidation in `LdapAttrTest.java` however it does not test reloading the plugin with classloader - only calls plugin's `load()` method.
