### ISSUE TITLE
NPE when searching (OpenGrok 0.11.1)

### ISSUE THREAD

**Issue by tomdz** [OpenGrok/OpenGrok#814]
When searching for anything, I get this error on the result page:
```
java.lang.NullPointerException
	at org.apache.lucene.index.SegmentReader$Norm.decRef(SegmentReader.java:409)
	at org.apache.lucene.index.SegmentReader.doClose(SegmentReader.java:815)
	at org.apache.lucene.index.IndexReader.decRef(IndexReader.java:163)
	at org.apache.lucene.index.DirectoryReader.doClose(DirectoryReader.java:828)
	at org.apache.lucene.index.IndexReader.decRef(IndexReader.java:163)
	at org.apache.lucene.index.IndexReader.close(IndexReader.java:1003)
	at org.apache.lucene.search.IndexSearcher.close(IndexSearcher.java:132)
	at org.opensolaris.opengrok.util.IOUtils.close(IOUtils.java:50)
	at org.opensolaris.opengrok.web.SearchHelper.destroy(SearchHelper.java:422)
	at org.apache.jsp.search_jsp._jspService(search_jsp.java:632)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

Turning on assertions makes it bail on the line before:

```
java.lang.AssertionError
	at org.apache.lucene.index.SegmentReader$Norm.decRef(SegmentReader.java:408)
	at org.apache.lucene.index.SegmentReader.doClose(SegmentReader.java:815)
	...
```

Indexing works fine as far as I can tell.

System info:
```bash
$ uname -a
Linux opengrok 2.6.18-308.1.1.el5 #1 SMP Wed Mar 7 04:16:51 EST 2012 x86_64 x86_64 x86_64 GNU/Linux

$ java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

$ cat /proc/sys/fs/file-max
3035108

$ ulimit -Hn
65536

$ ulimit -Sn
65536

```

**Comment by vladak** [comment]
This issue seems stale, closing. Feel free to reopen.
