### ISSUE TITLE
JavaScriptAnalyzer fails to parse large js file and stops indexing of all other repositories

### ISSUE THREAD

**Issue by whizard** [OpenGrok/OpenGrok#821]
I have a java script file (used for testing - don't ask me why we would have such a file ;) that causes OpenGrok's JavaScriptAnalyzer to fail and after the failure all subsequent repositories are not processed nor index (it causes an Out of Memory error etc.)

I can send you the file that causes the issue.

Thanks,

Paul

**Comment by sshock** [comment]
I ran into this as well, also on a file called big5.js.  OpenGrok choked on it with OutOfMemoryError.  I had to remove it from my src folder to get past the problem.  Here is a call stack:

2015-09-24 00:56:46.054-0600 SEVERE t30 IndexDatabase$1.run: Problem updating lucene index database:
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2367)
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:535)
    at java.lang.StringBuffer.append(StringBuffer.java:322)
    at java.io.BufferedReader.readLine(BufferedReader.java:363)
    at java.io.BufferedReader.readLine(BufferedReader.java:382)
    at org.opensolaris.opengrok.analysis.Ctags.readTags(Ctags.java:182)
    at org.opensolaris.opengrok.analysis.Ctags.doCtags(Ctags.java:173)
    at org.opensolaris.opengrok.analysis.plain.PlainAnalyzer.analyze(PlainAnalyzer.java:78)
    at org.opensolaris.opengrok.analysis.plain.AbstractSourceCodeAnalyzer.analyze(AbstractSourceCodeAnalyzer.java:69)
    at org.opensolaris.opengrok.analysis.AnalyzerGuru.populateDocument(AnalyzerGuru.java:307)
    at org.opensolaris.opengrok.index.IndexDatabase.addFile(IndexDatabase.java:606)
    at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:870)
    at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
    at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
    at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
    at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
    at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
    at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
    at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
    at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
    at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
    at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:383)
    at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:168)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by tarzanek** [comment]
I also wonder if using universal ctags here on github can mitigate this issue.
Alt filing a bug against them might help, they are active and alive unlike old exuberant ctags.

**Comment by santeriv** [comment]
universal-ctags commit https://github.com/universal-ctags/ctags/commit/ab9b5e93ecad935db5a84f74a31d455b8a48d562 seems to refer tackling of lengthy ctag files causing "OOM" and "disk-full" as referred in https://github.com/universal-ctags/ctags/issues/163#issuecomment-148881445

**Comment by tarzanek** [comment]
@santeriv this is very good news and it definitely means exuberant ctags is getting irrelevant
I will still add as part of #1014 a limiter on our side to also trim the line at the end (I will try to model it based on @masatake s fix, so we're in sync with universal ctags) and make it kick in for any other ctag than universal ...

**Comment by masatake** [comment]
I'm very happy to hear that universal-ctags solves the issue of OpenGrok.
