### ISSUE TITLE
History Generation fails due to svn not understanding --trust-server-cert option

### ISSUE THREAD

**Issue by ganeshgore555** [OpenGrok/OpenGrok#846]
How can I find if History cache is generated or not while using with/without db.

Also I am getting following error 

Jul 14, 2014 3:01:36 AM org.opensolaris.opengrok.util.Executor exec
WARNING: Non-zero exit status 1 from command [svn, log, --trust-server-cert, --non-interactive, --xml, -v, src/WFDB/Typ/PrimitiveDBTypesWFDB.typ@] in directory /ftp/oweb/grok/SVN_ROOT/OasysTCDb: svn: invalid option: --trust-server-cert
Type 'svn help' for usage.

Jul 14, 2014 3:01:36 AM org.opensolaris.opengrok.analysis.AnalyzerGuru getDocument
WARNING: An error occurred while reading history: 
org.opensolaris.opengrok.history.HistoryException: Failed to get history for: "/ftp/oweb/grok/SVN_ROOT/OasysTCDb/src/WFDB/Typ/PrimitiveDBTypesWFDB.typ" Exit code: 1
        at org.opensolaris.opengrok.history.SubversionHistoryParser.parse(SubversionHistoryParser.java:157)
        at org.opensolaris.opengrok.history.SubversionRepository.getHistory(SubversionRepository.java:223)
        at org.opensolaris.opengrok.history.SubversionRepository.getHistory(SubversionRepository.java:217)
        at org.opensolaris.opengrok.history.FileHistoryCache.get(FileHistoryCache.java:224)
        at org.opensolaris.opengrok.history.HistoryGuru.getHistory(HistoryGuru.java:210)
        at org.opensolaris.opengrok.history.HistoryGuru.getHistoryReader(HistoryGuru.java:173)
        at org.opensolaris.opengrok.analysis.AnalyzerGuru.getDocument(AnalyzerGuru.java:239)
        at org.opensolaris.opengrok.index.IndexDatabase.addFile(IndexDatabase.java:584)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:814)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:787)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:787)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:787)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:354)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:158)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Jul 14, 2014 3:01:36 AM org.opensolaris.opengrok.index.IndexDatabase optimize
INFO: Optimizing the index ... 
Jul 14, 2014 3:01:48 AM org.opensolaris.opengrok.index.IndexDatabase optimize
INFO: done
Jul 14, 2014 3:01:48 AM org.opensolaris.opengrok.index.IndexDatabase createSpellingSuggestions
INFO: Generating spelling suggestion index ... 
Jul 14, 2014 3:01:48 AM org.opensolaris.opengrok.index.IndexDatabase createSpellingSuggestions
INFO: done

**Comment by vladak** [comment]
If there is a viable way how to add server's CA to trust store for `svn log` and other subcommands to work, the option should be removed from `getAuthCommandLineParams()`.

**Comment by vladak** [comment]
According to http://www.microhowto.info/howto/configure_subversion_to_trust_a_given_ssl_certificate.html 

> Subversion can be told to trust a certificate by setting the ssl-authority-files property within the [global] section of the servers configuration file.

so the option can be safely removed.
