### ISSUE TITLE
Could not load codec 'Lucene46'

### ISSUE THREAD

**Issue by ymnick** [OpenGrok/OpenGrok#969]
The following error is presented trying to run indexing with local opengrok build forked from OpenGrok/OpenGrok:

java.lang.IllegalArgumentException: Could not load codec 'Lucene46'.  Did you forget to add lucene-backward-codecs.jar?
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:433)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:325)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:830)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:338)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:176)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene46' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene50]
        at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:109)
        at org.apache.lucene.codecs.Codec.forName(Codec.java:113)
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:423)
        ... 9 more

**Comment by tarzanek** [comment]
Did you cleanup old index ?

Start with clean dataroot ...

**Comment by ymnick** [comment]
I did now and it's running... Thanks!

**Comment by tarzanek** [comment]
we upgraded lucene, and there is no upgrade code in place (hence opengrok is not > 1.x ;) ... until upgrade won't be in place I won't vote for 1.x release)
closing this, marking as Q
